### ISSUE TITLE
Client will not delete 

### ISSUE THREAD

**Issue by 2592019238-ai** [superzanti/ServerSync#213] opened 2020-10-28 12:28 UTC
Serversync Version: 1.12.2

Minecraft Version: 1.12.2

Issue: The module client that has been deleted on my server will not be deleted
https://paste.ubuntu.com/p/yphXk8mCMz/
This is serversync-client.log
Already the latest version [serversync-3.7.0-alpha.2-all.jar]

**Comment by HaibaraGT** [comment] 2020-10-29 04:57
Hello, please try to use version 3.6.0, I also found this problem in the latest version.

**Comment by 2592019238-ai** [comment] 2020-10-31 13:56
> 您好，请尝试使用3.6.0版，我也在最新版本中发现了此问题。

3.6.0 Cannot synchronize other folders

**Comment by rheimus** [comment] 2020-11-02 03:45
I am not 100% sure what the issue being reported is, the client is not deleting a file that you are expecting to be removed?

Have you restarted ServerSync since deleting the file?

**Comment by rheimus** [comment] 2020-11-02 07:51
Hmm, looks like I haven't actually implemented the delete phase yet in the alpha versions. I'll add that to the top of the list.

**Comment by 2592019238-ai** [comment] 2020-11-02 10:06
> 我不是100％不确定所报告的问题是什么，客户端没有删除您希望删除的文件？
> 
> 自删除文件服务器端以来，您是否已重新启动ServerSync？

Restarted but not deleted

**Comment by 2592019238-ai** [comment] 2020-11-02 10:06
> 嗯，看来我还没有在alpha版本中实现删除阶段。我将其添加到列表的顶部。

Ok

**Comment by rheimus** [comment] 2020-11-06 09:36
`alpha.3` has reinstated the delete phase, it also allows you to configure push mode directories if you don't want a directory to delete files that don't exist on the server.

**Comment by HaibaraGT** [comment] 2020-11-06 12:12
> `alpha.3` has reinstated the delete phase, it also allows you to configure push mode directories if you don't want a directory to delete files that don't exist on the server.
> https://github.com/rheimus/ServerSync/releases/tag/3.7.0-alpha.3

Big problem, in the 3.7.0-alpha.3, flash back occurred on the server, the client all is well. I tried CMD and exe.Server log is as 
follows:
<
LOG:Loading language file: zh_CN
LOG:Starting server in mode: 2
LOG:Starting scan for managed files: 2020-11-6
LOG:Ignore patterns: {
  **/serversync-*.jar
  **/serversync-*.cfg
}
DEBUG:root dir: D:\minecraft_server
>

**Comment by rheimus** [comment] 2020-11-06 23:39
Flash back? Is that a crash.

Is there a stack trace or an error message that occurs, the log there does not seem to indicate any issues, when exactly does the issue occur?

**Comment by 2592019238-ai** [comment] 2020-11-07 10:31
> `alpha.3`已经恢复了删除阶段，如果您不希望目录删除服务器上不存在的文件，它还允许您配置推送模式目录。
> https://github.com/rheimus/ServerSync/releases/tag/3.7.0-alpha.3

After updating to "3.7.0-alpha.3", it is found that the clientmods on the server will not be fully synchronized, and the modules in the clientmods will be deleted
This is the serversync-client.log of the client:https://paste.ubuntu.com/p/qdGTPfPnSd/
This is the serversync-server.log of the server:https://paste.ubuntu.com/p/fXbWjVWgXJ/

**Comment by rheimus** [comment] 2020-11-07 11:20
Looks like the hash and path got switched for clientmods, I have fixed this in `alpha.4`.

**Comment by 2592019238-ai** [comment] 2020-11-18 13:18
> 似乎已将clientmods的哈希和路径切换了，我已在中修复此问题`alpha.4`。
> 
> 我可能还应该为设置行为编写一个自动测试。

> 
[url=https://sm.ms/image/IPXK3gTRFi5YAM9][img]https://i.loli.net/2020/11/18/IPXK3gTRFi5YAM9.png[/img][/url]
Is there a problem with me writing this way, if it is ok, I didn’t ignore it

**Comment by rheimus** [comment] 2020-11-19 03:17
@2592019238-ai Do you want to ignore every file in that directory?

If so the pattern that you want is a globstar `mods/memory_repo/**`

**Comment by 2592019238-ai** [comment] 2020-11-19 10:57
> @2592019238-ai Do you want to ignore the entire directory?
> 
> If so the pattern that you want is a globstar `mods/memory_repo/**`, in upcoming versions I will be implementing directory matching so you could just write `mods/memory_repo`, that is not working yet though.

Whenever you update, I need to republish the client, can you synchronize ServerSync?

**Comment by rheimus** [comment] 2020-11-20 06:05
#105 Would cover serversync updating itself, this is fairly high on the work list but I am making sure to get the actual sync working properly first.

**Comment by 2592019238-ai** [comment] 2020-12-14 10:34
> [＃105](https://github.com/superzanti/ServerSync/issues/105)将涵盖serversync更新本身，这在工作列表上相当高，但是我确保首先确保实际同步正常工作。

Whether to support when to exclude all files in the folder

**Comment by HaibaraGT** [comment] 2020-12-14 10:38
> > [＃105](https://github.com/superzanti/ServerSync/issues/105)将涵盖serversync更新本身，这在工作列表上相当高，但是我确保首先确保实际同步正常工作。
> 
> Whether to support when to exclude all files in the folder

https://github.com/superzanti/ServerSync/wiki/Ignore-&-include-lists-examples，You may need this, ignore the rules file to complete the operation.

**Comment by 2592019238-ai** [comment] 2020-12-14 10:40
> > > [＃105](https://github.com/superzanti/ServerSync/issues/105)将涵盖服务器同步更新本身，这在工作列表上相当高，但是我确保首先确保实际同步正常工作。
> > 
> > 
> > 是否支持何时排除文件夹中的所有文件
> 
> https://github.com/superzanti/ServerSync/wiki/Ignore-&-include-lists-examples
> 您可能需要这样做，忽略规则文件以完成操作。

This does not work. Can you, how do you set it up?

**Comment by HaibaraGT** [comment] 2020-12-14 10:55
> > > > [＃105](https://github.com/superzanti/ServerSync/issues/105)将涵盖服务器同步更新本身，这在工作列表上相当高，但是我确保首先确保实际同步正常工作。
> > > 
> > > 
> > > 是否支持何时排除文件夹中的所有文件
> > 
> > 
> > https://github.com/superzanti/ServerSync/wiki/Ignore-&-include-lists-examples
> > 您可能需要这样做，忽略规则文件以完成操作。
> 
> This does not work. Can you, how do you set it up?

`"file_ignore_list": [
      "**/serversync-*.jar",
      "mods/1.12.2/**",
      "**/serversync-*.cfg"
    ],`

Above is 3.7 version of the server. The json configuration files written in it, and "mods / 1.12.2 / * *", so you can ignore the mods folder 1.12.2 folder and all of the files in it.

**Comment by 2592019238-ai** [comment] 2020-12-14 11:37
> > > > > [＃105](https://github.com/superzanti/ServerSync/issues/105)将涵盖服务器同步更新本身，这在工作列表上相当高，但是我确保首先确保实际同步正常工作。
> > > > 
> > > > 
> > > > 是否支持何时排除文件夹中的所有文件
> > > 
> > > 
> > > https://github.com/superzanti/ServerSync/wiki/Ignore-&-include-lists-examples
> > > 您可能需要这样做，忽略规则文件以完成操作。
> > 
> > 
> > 这是行不通的。可以，如何设置？
> 
> `"file_ignore_list": [ "**/serversync-*.jar", "mods/1.12.2/**", "**/serversync-*.cfg" ],`
> 
> 以上是服务器的3.7版本。其中写入的json配置文件以及“ mods / 1.12.2 / * *”，因此您可以忽略mods文件夹1.12.2文件夹及其中的所有文件。

Why i have no effect

**Comment by HaibaraGT** [comment] 2020-12-14 12:46
> > > > > > [＃105](https://github.com/superzanti/ServerSync/issues/105)将涵盖服务器同步更新本身，这在工作列表上相当高，但是我确保首先确保实际同步正常工作。
> > > > > 
> > > > > 
> > > > > 是否支持何时排除文件夹中的所有文件
> > > > 
> > > > 
> > > > https://github.com/superzanti/ServerSync/wiki/Ignore-&-include-lists-examples
> > > > 您可能需要这样做，忽略规则文件以完成操作。
> > > 
> > > 
> > > 这是行不通的。可以，如何设置？
> > 
> > 
> > `"file_ignore_list": [ "**/serversync-*.jar", "mods/1.12.2/**", "**/serversync-*.cfg" ],`
> > 以上是服务器的3.7版本。其中写入的json配置文件以及“ mods / 1.12.2 / * *”，因此您可以忽略mods文件夹1.12.2文件夹及其中的所有文件。
> 
> Why i have no effect

My version is used “serversync-3.7.0-alpha.1”，You can try this configuration file, can ignore all folders and files.
[serversync-server.zip](https://github.com/superzanti/ServerSync/files/5688811/serversync-server.zip)

**Comment by rheimus** [comment] 2020-12-15 09:07
The attached config using `3.7.0-alpha.1` appears to ignore the files in `mods/1.12.2` for me. Can you outline exactly what result you want to achieve?

Notably, if you are using the alpha branch you probably want to use one of the more recent builds here https://github.com/rheimus/ServerSync/releases

**Comment by rheimus** [comment] 2021-03-06 01:21
Closing this as v4 has released and I have not been able to reproduce deletion issues.

Feel free to raise another issue if the problem persists in v4 onwards.

**Closed by rheimus** 2021-03-06 01:21 UTC
Labels: bug, server
