### ISSUE TITLE
Failed to obtain input/output streams for client

### ISSUE THREAD

**Issue by SecretGreatDeveloper** [superzanti/ServerSync#131] opened 2019-04-06 08:26 UTC
#### Issue: Failed to obtain input/output streams from client

<details> Well, I tried to sync my server with client, but I'm getting this kind of problem.
I tried three different versions of serversync, putting serversync in root directory and in mods folder. Btw. I'm running mc server on hosting website.
<pre>
finished loading config
root dir: C:\Users\Marcin\AppData\Roaming\.minecraft
Establishing a socket connection to the server...
< Connecting to server >
Creating input/output streams...
Failed to obtain input/output streams from client
Closing connections...
All of serversync's sockets to the server have been closed
Successfully closed all connections
Files updated
Errors occurred, please check ip/port details are correct. For a detailed log check the logs folder in your minecraft directory
</pre>

Does anybody have idea what's wrong?

</details>

**Comment by rheimus** [comment] 2019-04-08 07:04
Do you have access to the server side logs?

Seems to be failing to interact with the socket connection, but this could be any number of issues.

**Comment by SecretGreatDeveloper** [comment] 2019-04-14 21:41
Hello, sorry that I haven't written earlier. Logs are here: 

finished loading config
root dir: /home/servers/634085/home/servers/634085
Starting scan for sync files: Apr 14, 2019
Ignore patterns: serversync-*.jar, serversync*
Could not find the desired fields in the mod information file: version,name
Could not find the desired fields in the mod information file: version,name
Could not find a mod information file that matches: mcmod.info,neimod.info
Could not find the desired fields in the mod information file: version,name
Could not find the desired fields in the mod information file: version,name
Could not find a mod information file that matches: mcmod.info,neimod.info
Found 36 files that match user defined patterns
Creating new server socket
Now accepting clients...

**Comment by rheimus** [comment] 2019-04-15 09:06
Seems to be nothing out of the ordinary in the logs. The only fail point for sockets is general IO errors.

Could you investigate the following;
- Which OS are you using and which version (Windows / Linux etc)
- Which version of java do you have installed
- Are you running serversync from a permission restricted directory

Pretty much I am down to guessing that your system currently does not support java.net sockets or Object*Streams, other than that I really don't know, unfortunately.

**Comment by rheimus** [comment] 2019-07-31 07:24
Closing this for now, could not reproduce the issue.

**Closed** 2019-07-31 07:23 UTC
Labels: waiting for feedback
