### ISSUE TITLE
Investigating - Serversync file syncing issues.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#134] opened 2019-07-05 23:01 UTC
#### Issue: 
I am getting users saying they cannot connect 

"this is my current config."
# Configuration file

general {
    B:PUSH_CLIENT_MODS=true
}

serverconnection {
    I:SERVER_PORT=38067
}

rules {
    S:CONFIG_INCLUDE_LIST <
    >

    S:DIRECTORY_INCLUDE_LIST <
    config
    customdisc
    guides
    local
    mods
    pixelmon
    scripts
    >

    S:FILE_IGNORE_LIST <
    config/Discord-Integration.cfg
    mods/s-dcintegration-1.0.1-b.jar
    mods/s-Tiquality-FAT-1.12.2-GAMMA-1.5.3-r.jar
    >
}

misc {
    S:LOCALE=en_US
}

[serversync-server.log](https://github.com/superzanti/ServerSync/files/3364162/serversync-server.log)
[serversync-client.log](https://github.com/superzanti/ServerSync/files/3364163/serversync-client.log)

**Comment by rheimus** [comment] 2019-07-07 04:04
Client log looks like SS never managed to get to the connection phase.

Though the server log seems to suggest the client in question timed out on their connection for some reason.

Is this a constant failure, or intermittent?

**Comment by P3rf3ctXZer0** [comment] 2019-07-07 06:27
Intermittent

**Comment by P3rf3ctXZer0** [comment] 2019-07-07 06:27
I even occassionally have issues It works sporadically

**Comment by P3rf3ctXZer0** [comment] 2019-07-12 00:08
I forgot one key piece of information - when multiple people use serversync is when the issue occurs most often (I think like 3 people.)

**Comment by rheimus** [comment] 2019-07-12 05:08
Interesting, I'll look into the timeout. It should be one instance per client but it might be reaching outside itself.

**Comment by P3rf3ctXZer0** [comment] 2019-07-18 07:45
I just had a simple thought ... what if instead of placing serversync config in config folder it is placed in a separate config called ssconfig so you can also configure it to completely not press the config to clients - I think part of the reason it is having issues is because I think it scans itself at one point when it should not - ever.

**Comment by P3rf3ctXZer0** [comment] 2019-07-18 07:50
[serversync-server - Copy.txt](https://github.com/superzanti/ServerSync/files/3405344/serversync-server.-.Copy.txt)

**Comment by P3rf3ctXZer0** [comment] 2019-07-18 07:51
It was also still pressing files that I explicitly told it not to do. Also it seems to trip out after 192,000 files or more but I am going to study this in great detail today.

**Comment by P3rf3ctXZer0** [comment] 2019-07-18 16:43
Watching the log it deleted things with extensions it didn't understand. Maybe add a way to add accepted extensions or additional accepted extensions.

example 

.abc
.hocon <- pixelmon reforged uses this.
.twk <- inventory tweaks uses this.

**Comment by P3rf3ctXZer0** [comment] 2019-07-18 17:18
In other news multiple users are not getting client mod pushes.

**Comment by P3rf3ctXZer0** [comment] 2019-07-18 17:27
Okay so I just checked the users folder and ss is completely ignoring the PUSH CLIENT MODS setting

**Comment by P3rf3ctXZer0** [comment] 2019-07-18 17:28
@rheimus this is a huge problem.

**Comment by P3rf3ctXZer0** [comment] 2019-07-18 17:41
I tried changing the file name to not include any special characters and it still would not push that folder.

**Comment by rheimus** [comment] 2019-07-21 21:24
ServerSync has a feature for clients that allows them to refuse client mods from a server.

Has the client in question set "REFUSE_CLIENT_MODS" to true?

**Comment by rheimus** [comment] 2019-07-21 21:27
ServerSync only parses one type of file, that being '.jar' files.

If SS finds a .jar file it will look inside it for a minecraft mod information file, if it does not find one then it just treats the file like any normal raw file.

There should be no reason for specific file types to fail (outside of configuration issues) as SS just transfers the file byte for byte across the socket.

**Comment by rheimus** [comment] 2019-07-21 21:29
Could you send me a file tree dump or screenshot of your minecraft directory along with the serversync-server configuration file being used?

**Comment by P3rf3ctXZer0** [comment] 2019-07-21 23:23
Yeah not a problem

**Comment by P3rf3ctXZer0** [comment] 2019-07-21 23:31
[file-tree-dump.txt](https://github.com/superzanti/ServerSync/files/3415184/file-tree-dump.txt)
Is this what you wanted?
[serversync.zip](https://github.com/superzanti/ServerSync/files/3415185/serversync.zip)

**Comment by P3rf3ctXZer0** [comment] 2019-07-21 23:34
Please ignore the ignore list - during testing that was not actually there.

This was how the config list looked like during testing

https://gist.github.com/P3rf3ctXZer0/81afbc9c999057a012249f2976293bd9

**Comment by P3rf3ctXZer0** [comment] 2019-07-22 11:27
I wanted to let you know I found out that after syncing the same file set to myself 3 times I started failing to get files too. Maybe have a ip sanity check for client as well as for server that is why I felt unique file check felt best maybe place and md5 id per folder? So basically if server-sync detects that any file does not match what is pushed have it delete any files that do match and re-download them - then do another sanity check. If the sanity is valid write and md5 number and move on to the next folder. I should never fail to recheck files at least once. Against both file size and name. If it just checks name - that would allow a type of failure and would allow users to tamper with file in a way a would could be malicious. I believe too that if you have a server log that keeps - the IPV4s with a single md5checksum or some identifier this too would allow ss to make sure all the same requested files are sent. Try it once delete all the files multiple times and on a remote ip have someone else get those files and you will see what I am talking about. Serversync after a bit starts to believe it sent those files - even though it didn't - like a scatter brained secretary.

**Comment by P3rf3ctXZer0** [comment] 2019-07-22 11:45
I believe if you see first hand what I am experiencing you get a much greater understanding of what is going wrong since clearly we are also in different time-zones.

**Comment by P3rf3ctXZer0** [comment] 2019-07-22 12:20
He he he ... helps if I turn the listener on ...

**Comment by P3rf3ctXZer0** [comment] 2019-07-22 12:37
Um I forgot to add things from file tree print but this is the current client mods directory.
![2019-07-22 07_36_47-192 168 1 4 - Remote Desktop Connection](https://user-images.githubusercontent.com/10351221/61632899-94c96380-ac53-11e9-9fe8-04719e8d2527.jpg)

**Comment by P3rf3ctXZer0** [comment] 2019-07-22 12:38
This is what happened when using souly server-sync
![2019-07-22 07_38_15-Window](https://user-images.githubusercontent.com/10351221/61632962-b75b7c80-ac53-11e9-8731-384aef7c499f.jpg)

**Comment by P3rf3ctXZer0** [comment] 2019-07-22 12:39
![2019-07-22 07_38_15-Window](https://user-images.githubusercontent.com/10351221/61633039-dd811c80-ac53-11e9-9a71-16123ebcbef7.jpg)

**Comment by P3rf3ctXZer0** [comment] 2019-07-22 12:40
![2019_07_22_07_39_09_Window](https://user-images.githubusercontent.com/10351221/61633083-ef62bf80-ac53-11e9-8840-5d21999f17f0.jpg)

**Comment by P3rf3ctXZer0** [comment] 2019-07-22 13:11
At this point I have given you everything I can ... the rest is up to you.

**Comment by rheimus** [comment] 2019-07-24 04:06
ctm should not be a client mod if it is a required dependency of chisel.

Client mods were designed to be mods that are completely optional, i.e. you can connect to the server without having them present. (NEAT, Optifine, etc)

Your client config has also set REFUSE_CLIENT_MODS=true, this is telling ServerSync to not sync anything that comes from the servers 'clientmods' directory.

**Comment by rheimus** [comment] 2019-07-24 04:23
SS currently does file comparison in the following cascade.

1. Do the file names match (files are not equal if this fails)
2. Do the files exist in the same location (files are not equal if this fails)
3. Do the files have matching hashes (files are not equal if this fails)

**Comment by rheimus** [comment] 2019-07-24 07:28
I was interested in setting up some auto testing, the multiple sync's failing would be a decent test case.

Might look into serenity or something.

**Comment by P3rf3ctXZer0** [comment] 2019-07-24 13:28
Okay so ctm cannot be a universal mod as it crashes the server - I know stupid and that does not absolve the whole client folder failing to push either though.

**Comment by rheimus** [comment] 2019-07-25 07:25
Don't worry about my rambling 😊, serenity is an auto testing framework / pattern for software (http://www.thucydides.info/#/).

The client folder is not being transferred due to the client config telling it not to. To transfer 'clientmods' you need the following pair of configuration settings:
### Server
PUSH_CLIENT_MODS=true

### Client
REFUSE_CLIENT_MODS=false

**Comment by P3rf3ctXZer0** [comment] 2019-07-25 12:38
I did try that I swear ...

**Comment by P3rf3ctXZer0** [comment] 2019-07-25 15:24
Gah ... how many ways can I say I tried everything on my end !?

**Comment by rheimus** [comment] 2019-07-26 03:30
I'll need accurate data to be of much assistance, the above configurations were set up in a way that would manifest exactly what you are seeing.

Could you provide a zip of your server instance, I can not currently reproduce the issue locally.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 04:39
sure ...

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 04:47
https://www.dropbox.com/s/xww9ahjxgy1wthg/mc-1.12.2-FromTheAshes-ss.zip?dl=0

I have to say again though - for best raw expirence just use server sync on that pack I gave you. I did update a few files before giving them to you - only to match the newest pack release ... I doubt you can even find the error locally - do you have a far away server and ip you are using for testing?

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 04:48
Please consider using this https://github.com/superzanti/ServerSync/issues/134#issuecomment-513752560

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 04:50
Besides - testing from a users perspective will give you the most raw experience.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 04:53
Interesting - at one point the serversync client config was reset ...

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 04:56
I didn't do it ... - maybe after a failed attempt to sync - does it a have a fallback routine?

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 04:58
![2019-07-25 23_57_18-Window](https://user-images.githubusercontent.com/10351221/61926849-ffbab900-af37-11e9-9e0d-afd89156ec8a.jpg)

This is what it looked like before the reset of the config ...

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 04:59
That picture is directly off the remote server host. But when I opened up that pack I gave you in comment 134 it said ip was set to 127.0.0.1 instead of the ip you see in that image ...

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:03
Cool this time it didn't send the configs for some mods ... 
![2019-07-26 00_02_55-Window](https://user-images.githubusercontent.com/10351221/61927037-c898d780-af38-11e9-9c9d-9bb89ea4ca00.jpg)
Right Side is Server Config 
Left Side is Client Config when obtained by serversync.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:05
Its trivial but annoying the server allows you to see FlatColoured Blocks in JEI but the client version was set to ignore - so they don't match. Let me check and see how many configs failed to send. Okay so good news it was the one config ... but the fact that it is not sending all configs means it will break in different ways at some point.

**Comment by rheimus** [comment] 2019-07-26 05:06
Indeed, you are synchronizing the config folder. The serversync configs are not currently protected so they will be deleted/modified unless explicitly ignored in the ignore lists.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:06
Why would you not just have it ignore it by default?

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:07
That does not fix other things failing to send.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:07
As you can see by my posts.

**Comment by rheimus** [comment] 2019-07-26 05:07
That was the plan, though currently the ignore pattern is wrong.

It is ignoring serversync*, but that will only ignore anything it finds at the top level directory.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:08
So what about just moving the location serversync is being saved?

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:08
don't have it generate in config subfolder.

**Comment by rheimus** [comment] 2019-07-26 05:09
I can just fix the ignore pattern so that it is looking for the right thing 😊

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:09
Okay - that sounds better - the other thing is make wild cards work so we don't need to manually set deeper folders.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:10
I think unless user explicitly sets it should count recoursive subfolders as things it should mimic too.

**Comment by rheimus** [comment] 2019-07-26 05:11
That would break the spec for glob patterns, recursive search is defined by '**' double star.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:12
Ps I am staying up soley to help you - so when you have a build to test let me know immediately cause I am getting tired. 

So when a user sets add "config/myconfig**" that makes all recursive folders included as well?

**Comment by rheimus** [comment] 2019-07-26 05:14
Yeah. Though glob patterns are only supported at the moment in the ignore lists.

The directory include list is recursive by default.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:15
Oh well maybe do me and the world a favor and comment out and add an explination and usage instructions <- I have no memory so essentially you could end up reteaching me 80x's

**Comment by rheimus** [comment] 2019-07-26 05:16
https://github.com/superzanti/ServerSync/wiki/Ignore-&-Include-lists

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:16
Would you be shocked if I said I barely understand the explanations in the wiki?

**Comment by rheimus** [comment] 2019-07-26 05:16
Probably worth adding a link to the wiki in the main readme.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:18
Look at it this way - pretend you are teaching code to a 6 year old. - They have a general feel but are easily distracted by big words and lengthy sketches also easily intimated by things they don't get.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:20
How long will it take to make the code alterations I am getting really tired.

**Comment by rheimus** [comment] 2019-07-26 05:20
There is a link to a live playground 'globtester' which lets you interactively test exactly which patterns do what.

Though I could probably add story style documentation in there.

**Comment by rheimus** [comment] 2019-07-26 05:21
There is unlikely to be any changes to test for a while, I have to try and reproduce the problem first.

**Comment by P3rf3ctXZer0** [comment] 2019-07-26 05:21
Sadness ... I think I may have done legit all I can ... farewell friend ... please let me know if I can help again ... night.

**Comment by rheimus** [comment] 2019-08-22 04:34
There is an early access peek at the new file sync available in my fork if you are interested, note that it does not currently support clientmods: https://github.com/rheimus/ServerSync/releases

**Comment by P3rf3ctXZer0** [comment] 2019-08-22 12:20
I am always happy to test things for you.

**Comment by rheimus** [comment] 2019-08-27 07:05
Updated alpha.1 to re-add clientmods functionality.

**Comment by rheimus** [comment] 2019-08-27 07:07
As a part of the new file sync I also added in a retry phase. If for whatever reason one of the files fails to sync the client will try a second time.

**Comment by rheimus** [comment] 2019-08-28 07:38
All good, it will be in alpha for a while until I can get some proper end to end testing set up for it. There are almost certainly bugs in the new process that I have not catered for.

**Comment by P3rf3ctXZer0** [comment] 2019-08-28 23:12
Yeah - hopefully sometime after the 15th I will have what I need to test things again.

**Comment by rheimus** [comment] 2020-11-07 00:02
File sync has had major changes from 3.x.x, closing this one for now. Feel free to raise new issues if problems persist.

**Closed by rheimus** 2020-11-07 00:02 UTC
Labels: bug
