### ISSUE TITLE
sync config or other directory

### ISSUE THREAD

**Issue by kaiserdj** [superzanti/ServerSync#168] opened 2020-03-28 18:37 UTC
#### Issue: 

First of all congratulations on the mod, it is incredibly useful.

I have a problem with the synchronization, to synchronize mods it works perfectly, but I can synchronize for example the entire config folder, excluding some file.

I have tried in a thousand ways and I have not succeeded, I crashed the entire server

Thank you

**Comment by kaiserdj** [comment] 2020-03-30 00:51
Crash report: 
[crash-2020-03-30_02.47.27-server.txt](https://github.com/superzanti/ServerSync/files/4400262/crash-2020-03-30_02.47.27-server.txt)
Config:
[https://pastebin.com/raw/0NSTZesr](https://pastebin.com/raw/0NSTZesr)

**Comment by rheimus** [comment] 2020-03-31 09:53
ServerSync is failing to access one of the configured directories.

Do you have special permissions set on config?

**Comment by kaiserdj** [comment] 2020-03-31 09:55
I do not have any special permission configured, I am from windows 10 and I am the administrator of the pc with an administrator account and the configuration of the serversync you have attached above

**Comment by rheimus** [comment] 2020-03-31 09:59
Hmm, it's getting a null pointer while trying to gather the files available for sync. I'll load up a 1.12 test server and see if I can reproduce it.

**Comment by kaiserdj** [comment] 2020-03-31 10:04
I think it may be because I am trying to share configuration files that the server itself is using for mods, so it does not have access to those files because they are currently in use.

It can be that?

**Comment by rheimus** [comment] 2020-03-31 10:07
Hmm, possibly if the server is holding a lock level on the file that prevents 'read' access.

**Comment by rheimus** [comment] 2020-03-31 10:09
What version of Java do you have installed?

**Comment by kaiserdj** [comment] 2020-03-31 10:12
> What version of Java do you have installed?

jdk: 1.8.0_241

**Comment by rheimus** [comment] 2020-03-31 10:23
[serversync-3.4.0-debug.jar.zip](https://github.com/superzanti/ServerSync/files/4408370/serversync-3.4.0-debug.jar.zip)
Give this debug version a try. I have tweaked the file collection to avoid nulls and added some debug logging around it.

**Comment by kaiserdj** [comment] 2020-03-31 10:57
I have used the version that you have indicated to me, I have noticed that the "Contents of getDiffableFilesFromDirectories", it keeps outputting files that it is supposed to ignore

- Config: [serversync-server.cfg.txt](https://github.com/superzanti/ServerSync/files/4408540/serversync-server.cfg.txt) (I upload it in txt format because in cfg it doesn't leave github)

- crash-reports: [crash-2020-03-31_12.48.26-server.txt](https://github.com/superzanti/ServerSync/files/4408503/crash-2020-03-31_12.48.26-server.txt)

- Console: https://pastebin.com/raw/tuBLQRTS

- Logs: [logs.zip](https://github.com/superzanti/ServerSync/files/4408520/logs.zip)

I hope it can help you discover what is happening and thx ^^

**Comment by rheimus** [comment] 2020-03-31 10:59
Yep that log output is just every file in every configured directory. It has not filtered out ignored files at that stage.

**Comment by rheimus** [comment] 2020-03-31 11:05
I'll pick this up tomorrow and have a dig into it further.

The only noteworthy oddity in the list of files is this one: `mods\# LibLoader.jar`, it shouldn't be causing an issue but it is a rather odd file name.

Looks like we are getting the same null pointer so the issue is somewhere deeper than the initial file fetch.

**Comment by rheimus** [comment] 2020-04-02 05:06
Well I am basically at a loss with this one, the null pointer appears to be getting thrown inside java functions.

Do you get this same issue if you run ServerSync manually without forge loading it?

**Comment by kaiserdj** [comment] 2020-04-02 08:58
With the version that you have told me, it does not give me a single problem, it is incredible ❤️ 💯 
Just in case, I show my config and data in case you want to see something that works for you

**Comment by rheimus** [comment] 2020-04-02 10:42
Included configs is only relevant if you add entries to the config_include_list. Its essentially a 'whitelist' version of sharing configs.

Thanks for the logs! Will be useful to look into why this may have been solved.

**Comment by rheimus** [comment] 2020-10-10 00:30
Closing this as task complete.

**Closed by rheimus** 2020-10-10 00:30 UTC
Labels: bug
