### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by SchlafenderFox** [superzanti/ServerSync#130] opened 2019-03-21 07:52 UTC
#### Issue: Server forhe crash

<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>
<
[07:48:09] [Server thread/INFO] [STDOUT]: [runme.Main:main:47]: Loading language file: en_us
[07:48:10] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ServerSync (com.superzanti.serversync)

Caused by: java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_191]
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_191]
        at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[?:1.8.0_191]
        at java.awt.EventQueue.invokeLater(EventQueue.java:1294) ~[?:1.8.0_191]
        at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1295) ~[?:1.8.0_191]
        at runme.Main.main(Main.java:50) ~[Main.class:?]
        at com.superzanti.serversync.forgeloader.ForgeLoaderNET.startServersync(ForgeLoaderNET.java:17) ~[ForgeLoaderNET.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624) ~[server.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[server.jar:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[07:48:10] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify sun.reflect.GeneratedMethodAccessor9 (untransformed name: sun.reflect.GeneratedMethodAccessor9)
[07:48:10] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/administrator/minecraft-server/./crash-reports/crash-2019-03-21_07.48.10-server.txt
[07:48:10] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[07:48:10] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[07:48:10] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at appeng.core.AppEng.serverStopped(AppEng.java:271)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.reflect.Method.invoke(Method.java:498)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.reflect.Method.invoke(Method.java:498)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.reflect.Method.invoke(Method.java:498)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:847)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[07:48:10] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.Thread.run(Thread.java:748)
[07:48:10] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
[07:48:10] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving worlds
>
</pre>
</details>

**Comment by rheimus** [comment] 2019-03-25 02:21
https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror
https://github.com/Microsoft/vscode-arduino/issues/644

Looks like an issue with your java environment setup, I'll look into why SS is dependent on assitive technologies though.

**Comment by GabrielSerealia** [comment] 2019-05-28 06:48
I was thinking maybe it had something to do with the UI, because I'm currently running the headless version of Java and I'm assuming he is too

**Comment by GabrielSerealia** [comment] 2019-05-28 07:07
Actually I can't seem to get this running on a headless linux installation. I'm using a clean install of ubuntu-server 18.04 with default-jre installed. It runs fine on Windows 10

**Comment by rheimus** [comment] 2019-05-28 07:40
Most likely needs some re-design to decouple the functionality of SS from awt.

**Comment by GabrielSerealia** [comment] 2019-05-28 07:44
I found a workaround for me was running it outside the docker image using headless java. I installed default java on the main machine and ran the jar that way. Works for intended use now. I just wanted to say this mod is something I wish I had years ago when running a custom mod pack. Thank you for making it c:

**Comment by GabrielSerealia** [comment] 2019-05-28 08:10
I know I should create a new issue for this, but when I try to run ServerSync in tmux as soon as I close my terminal session ServerSync dies. This includes a tmux session started detached.

**Comment by GabrielSerealia** [comment] 2019-05-28 08:24
Just a work around for anyone using my setup so ServerSync doesn't close when you exit the terminal. 

`tmux new -d -s ServerSync 'unset DISPLAY; java -jar serversync-2.6.17.jar server'`

This will create a tmux session and force ServerSync to not use an X11 display

Also Im sorry for spamming your inbox @rheimus

**Comment by rheimus** [comment] 2019-05-28 08:25
Most interesting indeed, some lovely new avenues of research to do 😊

**Comment by kmccmk9** [comment] 2019-06-07 04:16
Just want to comment and say I am also having this problem. Using a Minecraft hosting provider running Linux.

**Comment by GabrielSerealia** [comment] 2019-06-07 04:24
Could you Pastebin the error message?

**Comment by kmccmk9** [comment] 2019-06-08 04:15
https://pastebin.com/R1yC3kxM

**Comment by GabrielSerealia** [comment] 2019-06-09 01:44
Ask your host if they can install the regular java package for your VM

**Comment by kmccmk9** [comment] 2019-06-09 01:53
What do you mean by regular Java?

**Comment by GabrielSerealia** [comment] 2019-06-09 01:56
You probably have `openjdk-8-jre-headless` which does not have the required dependencies you need. You need `default-jre` or one of the versions.

**Comment by kmccmk9** [comment] 2019-06-09 01:59
Ok I will let them know. Strange that this only happened when we updated
forge.

**Comment by GabrielSerealia** [comment] 2019-06-09 02:02
I mean I could be completely wrong, the work around I had was to run it standalone from the server

**Comment by rheimus** [comment] 2019-06-10 08:33
Sadly I can not reproduce the error in WSL with headless openjdk 11.

Looks like SS was oddly invoking 'doLater' in the main thread when initializing the translation strings. It was doing so in order to system out a console message, which is quite an odd thing to do.

I have removed this use of swing utils, might help with this issue as it was where @kmccmk9 was hitting the error.

**Comment by rheimus** [comment] 2019-07-31 07:25
Closing with no feedback, I can not reproduce this.

**Closed by rheimus** 2019-07-31 07:25 UTC
Labels: bug, waiting for feedback
