### ISSUE TITLE
Version 2.3 Not Deleting Old .jar Files.

### ISSUE THREAD

**Issue by Junrall** [superzanti/ServerSync#15] opened 2015-06-12 03:49 UTC
Aw man.... I thought it was working, but realized that I was looking at the wrong folder.
The problem still persists with version 2.3

It's the same as before. ServerSync downloads the new jar file but is unable to delete the old one.

I checked the task manager to be sure that Java didn't stay running after closing Minecraft.
If you like I can upload my entire MultiMC folder to drop box so that you can run exactly what I have. It's fairly large as I have about 130 mods.

**Comment by superzanti** [comment] 2015-06-12 06:36
Yes, go ahead and do that. I will test it out, because it's working just fine for me currently. When did you download version 2.3? I didn't upload all that long ago.

**Comment by Junrall** [comment] 2015-06-12 15:41
I just sent you a private message through curse. It has the dropbox link to my setup. It should have my server already setup in the multiplayer window. If not, let me know and I will message you the IP.

**Comment by superzanti** [comment] 2015-06-12 15:52
Great. It might be a few hours till I can connect. Will you be able to chat live at all?

**Comment by Junrall** [comment] 2015-06-12 16:29
Unfortunately I'm not able to chat. I'm a service tech. .. and am on the job all day.

**Comment by superzanti** [comment] 2015-06-12 17:32
I am on Job all day as well.
By a few hours I meant... About 5-6 hours from now.

**Comment by superzanti** [comment] 2015-06-12 22:54
Junrall, just to confirm, did you try to update your clients while they still had version 2.2?

**Comment by Junrall** [comment] 2015-06-12 23:54
Nope.  I manually deleted the 2.2 version then dropped in 2.3.

**Comment by superzanti** [comment] 2015-06-12 23:55
Test it for me with something that's not a jar file. Put something like an image in the folder and tell me if it deletes it. Then try another mod like optifine. I'm thinking it might be mod-specific.

**Comment by Junrall** [comment] 2015-06-13 03:10
Just an idea or two to throw out there...

Maybe ServerSync (on the client side) could generate a file that lists the names of pending jars to be deleted. Then when the client is restarted and before the jars are loaded, read the generated file and delete whatever is in it's list.

Also, maybe a quicker way to check for updates....
1 - Have both the client and server, at startup, generate a file that contains a list of all files within the mods folder and configs folder.
2 - When the client makes a check for updates, down load the generated file from the server and compare it's list to the client's generated file list. Create a ChangePending file with a list of file names to be downloaded and deleted.
3 - When Minecraft is restarted and before the jars/configs are loaded, look at the ChangePending file and download or delete any pending file listed.
4 - Delete the ChangePending File.

Just a thought, from one who knows next to nothing about programming, but has dabbled over the years. :D

**Comment by superzanti** [comment] 2015-06-13 04:17
The problem is, windows can't delete the file because java has a lock on the files to be deleted. Minecraft holds that lock, so if you restart the client, the lock will still be there.

I hope that gets it across a little bit.

It works on linux very well because java manages it's own lock instead of windows doing it for java.

I feel the only way I can do it well is to create an entire new application. I will get this mod done, so do not fret. But it might be a month till it's completed :/

**Comment by Junrall** [comment] 2015-06-13 04:43
No worries :)

This particular windows / java  issue has been around for years apparently.

Regardless, this is probably one of the most useful tools I've come across for server and clients.
If you get this up and running for windows at some point, I'll send you a friggin keg of beer! Lol

**Comment by superzanti** [comment] 2015-06-13 06:17
OH I will :)

**Comment by superzanti** [comment] 2015-06-15 02:36
Junrall, I'll have you know this issue is fixed in 2.4.

Note: I had to do a workaround in windows to get this working. So if you look in the mods directory it will appear as if the file is still there, but I assure you forge will not load these files. On the next update from the server these files will be removed completely.

It can be a bit messy but it works for now.

When I redevelop this mod sometime in the next month it will be much better. But hey, like I said. It works.

**Closed by superzanti** 2015-06-15 02:36 UTC
