### ISSUE TITLE
Can't use other ports

### ISSUE THREAD

**Issue by indoorsNB** [superzanti/ServerSync#53] opened 2017-03-16 23:13 UTC
https://github.com/indoorsNB/tuchuang/raw/master/IMG_0515.PNG

**Comment by rheimus** [comment] 2017-03-21 06:15
Could I get some further environment information about this case.

- Serversync version being used (forge-loaded, normal)
- Steps to reproduce the issue

Currently I have not been able to reproduce a null pointer issue when altering the port serversync is working on.

**Comment by indoorsNB** [comment] 2017-03-21 06:18
Serversync 2.6.2
1.7.10
how to reproduce:change the port in server config and restart the .sh

**Comment by rheimus** [comment] 2017-03-21 06:26
Try using Serversync 2.6.8 in the releases tab. Is quite possible I have fixed this issue already.

- Forge loaded will load the server when you start forge (must be in the mods folder)
- Normal ServerSync must be in the directory above mods, can start the server version of SS with the argument "server" passed to serversync
- java -jar serversync.jar server

**Comment by rheimus** [comment] 2017-03-23 04:20
Closing due to not being able to reproduce the issue.

Feel free to reopen should the latest version of SS not solve the problem.

**Closed by rheimus** 2017-03-23 04:20 UTC
Labels: bug

**Comment by ElSaam** [comment] 2017-06-05 11:33
Do i need to put same as server or different? If i put different i can't connect and if i put same the server says this port already running and shuts down.
