### ISSUE TITLE
Simplify exclusion / inclusion lists

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#71] opened 2017-05-01 02:47 UTC
#### Serversync Version: 
serversync-2.6.13.jar
#### Minecraft Version: 
XX
#### Issue: 
Ignoring larger mod lists.

https://gist.github.com/P3rf3ctXZer0/f69bdc7799abbb3ad5c0a9604d26b5cd

**Comment by rheimus** [comment] 2017-05-01 04:10
Not entirely sure what the problem is with this one?

Are you synchronizing a large amount of mods and they aren't all being transferred?

Do you have the servers log, fml-server-latest usually.

**Comment by P3rf3ctXZer0** [comment] 2017-05-01 04:38
Okay so I found out it only does that if you add the config folder to the include config category.

Also yes

**Comment by rheimus** [comment] 2017-05-01 05:21
include_config_list is built as a white-list
````xml
include_config_list <
    config/**
>
````

Would essentially be saying only include the configs that match:
- config/config/**

Which would probably mean that SS would ignore all of your configs, unless a mod adds a config folder in the config folder which would be somewhat irregular.

**Comment by P3rf3ctXZer0** [comment] 2017-05-01 05:33
I did that XD

**Comment by rheimus** [comment] 2017-05-01 05:33
Logic around these ignore lists does need some streamlining though.

**Comment by rheimus** [comment] 2017-05-01 05:36
As of the moment if you add config to the directory_include_list then config_include_list is not used.

**Comment by P3rf3ctXZer0** [comment] 2017-05-01 05:44
Okay thanks for the update.

**Comment by rheimus** [comment] 2017-05-01 22:25
Going to track this as the task to simplify the exclusion lists

**Comment by cragrim** [comment] 2017-07-14 12:10
If I wanted to add some configs to be ignored like jei, mouse tweaks and inv tweaks how would I do that? Can I add them to S:MOD_IGNORE_LIST or will this just ignore mods?

**I.e. ignore the following ones:**
\config\jei
MouseTweaks.cfg
InvTweaks.cfg
```
 S:MOD_IGNORE_LIST <
    \config\jei\*
   MouseTweaks.cfg
   InvTweaks.cfg
    >
```

Or maybe I have configured the following incorrectly?

**serversync-client.cfg**
```
# Configuration file

general {
    B:REFUSE_CLIENT_MODS=false
}

serverconnection {
    S:SERVER_IP=sandsten.spelar.se

    I:SERVER_PORT=25565
}

rules {
    S:CONFIG_INCLUDE_LIST <
       config
    >

    S:MOD_IGNORE_LIST <
    >
}

misc {
    S:LOCALE=en_US
}
```

**serversync-server.cfg**
```
# Configuration file

general {
    B:PUSH_CLIENT_MODS=true
}

serverconnection {
    I:SERVER_PORT=25565
}

rules {
    S:CONFIG_INCLUDE_LIST <
    >
        config

    S:DIRECTORY_INCLUDE_LIST <
        config
        mods
    >

    S:MOD_IGNORE_LIST <
    >
}

misc {
    S:LOCALE=en_US
}
```

**Comment by cragrim** [comment] 2017-07-14 12:46
I realized now that I added the config folder to the include directory list and that this overrides configs to be included. Basically I want to include all configs except some specific client side settings.

I.e. a config blacklist instead of a whitelist.
Is this possible as it is now?

**Comment by cragrim** [comment] 2017-07-14 13:40
Adding config files to the Mod ignore appears to have worked for me!

**The following serversync-server.cfg will ignore JEI, inv tweaks, mousetweaks and fps settings**
```
# Configuration file

general {
    B:PUSH_CLIENT_MODS=true
}

serverconnection {
    I:SERVER_PORT=25565
}

rules {
    S:CONFIG_INCLUDE_LIST <
    >

    S:DIRECTORY_INCLUDE_LIST <
        config
        mods
    >

    S:MOD_IGNORE_LIST <
				config/jei/*
				config/InvTweaks*
				config/MouseTweaks*
				config/betterfps*
				config/foamfix*
    >
}

misc {
    S:LOCALE=en_US
}
```

**Comment by rheimus** [comment] 2017-07-15 00:04
Woo whitespace galore 😀, yes as it stands at the moment the 'mod' ignore list will affect everything that is added to the directory includes.

Have been meaning to change that to File ignore list to be more generic

**Comment by rheimus** [comment] 2017-07-15 00:07
Oh, looks like I did already 😋 https://github.com/superzanti/ServerSync/blob/master/src/main/java/com/superzanti/serversync/SyncConfig.java

It just looks for either the old mod list or the newer file list

**Closed** 2017-09-10 01:14 UTC
Labels: backlog, enhancement
